# Generated by Django 4.0.5 on 2022-06-07 02:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(choices=[('AS', 'Applied Science'), ('CS', 'Computer Science'), ('Civil', 'Civil Engineering'), ('EC', 'Electronics and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=10)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('designation', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('HOD', 'HOD')], default='Assistant Professor', max_length=30)),
                ('profile_image', models.ImageField(upload_to='profile')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
